### ISSUE TITLE
active vs used memory

### ISSUE THREAD

**Issue by zllovesuki** [valeriansaliou/node-vigil-reporter#1]
Would it make more sense to use “active” memory as “used” includes buffers and cache which will be allocated to application uses when needed?

**Comment by valeriansaliou** [comment]
That could indeed be used instead; but both stats are useful and depending on the use of Vigil, either one or the other is useful in determining the load of a server. I accept PRs, but please keep the "used" memory too and make it usable instead of "active" via an option parameter when booting up the library.
